version: '3'
services:
   sandoz-ar-web:
     image: image_name:tag
     container_name: name
     working_dir: /var/www
     ports:
       - 80:80
     networks:
       - app-network
networks:
  app-network:
    driver: bridge
