version: '3'
services:
  database:
    image: mysql:5.7
    container_name: database
    volumes:
      - ./db_data/:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=database     
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - app-network
  app:
    image: name:fpm
    container_name: app
    environment:
      - DB_DATABASE=database
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
    restart: unless-stopped
    networks:
      - app-network
  amigos_webserver:
    image: name:webserver
    container_name: webserver
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - app-network
networks:
  app-network:
volumes:
  db_data: